### ISSUE TITLE
Fields in inspector overlap with IfAttribute and unityEvent

### ISSUE THREAD

**Issue by Paul-1379** [DarkRewar/BaseTool#119]
When using a simple script like: 
`using BaseTool;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.Serialization;

public class SimpleBugScript : MonoBehaviour
{
    [FormerlySerializedAs("_ifBool")] [SerializeField] private bool ifBool;
    [SerializeField, If(nameof(ifBool))] private UnityEvent unityEvent;
    [SerializeField, If(nameof(ifBool))] private bool boolValue;
}`
The fields in the inspector are not showed correctly:

https://github.com/user-attachments/assets/5e7b051e-1292-4aa1-b386-cf61042baae3

The bug is also present in unity 2022

**Comment by DarkRewar** [comment]
Duplicates #94
