### ISSUE TITLE
Add create parent for selected in a new menu item

### ISSUE THREAD

**Issue by Paul-1379** [DarkRewar/BaseTool#77]
Add a new menu item which allows you to create a parent gameObject for the different selected objects,
like in this part of this video:
https://youtu.be/mgsLb3TKljk?si=3ehHTdDbw22Y4gFG&t=83

**Comment by DarkRewar** [comment]
But, does this option not exist yet? 
<img width="365" alt="image" src="https://github.com/DarkRewar/BaseTool/assets/7771426/71dd52c2-dc5f-47b9-ac61-eb35607ecde8">

**Comment by Paul-1379** [comment]
Ah! I did not know, sorry!
